# Generated by Django 5.2 on 2025-01-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_owner_i_c557f2_idx',
            old_name='api_note_owner_titl_idx',
        ),
    ]
